version: '3'

services:
  db:
    image: postgres
    container_name: local_pgdb
    ports:
      - "10123:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  back-end:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: BackendCinema
    ports:
      - "8080:8080"

    depends_on:
      - db

    environment:
      SPRING_APPLICATION_JSON: '{
                "spring.application.name ": "cinema-app",
                "spring.datasource.url"  : "jdbc:postgresql://db:5432/postgres",
                "spring.datasource.username" : "postgres",
                "spring.datasource.password" : "postgres",
                "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
                "spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access" : "false",
                "spring.jpa.hibernate.ddl-auto" : "update"
              }'


volumes:
  local_pgdata:


