create table cinema
(
    id      integer      not null
        primary key,
    name    varchar(255) not null,
    city    varchar(255),
    is_open boolean,
    rating  text
);

alter table cinema
    owner to postgres;

INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (1, 'Quitzon and Sons', 'Pesnica pri Mariboru', false, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (52, 'arg', 'Warsaw', true, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (2, 'Ankunding LLC', 'Rodniki', true, 'Donec quis orci eget orci vehicula condimentum.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (3, 'Kling-Donnelly', 'Nanping', true, 'Donec dapibus.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (4, 'Morar, Purdy and Stark', 'Nangka', true, 'Vestibulum sed magna at nunc commodo placerat.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (5, 'Bechtelar-Schowalter', 'Lat Lum Kaeo', true, 'Morbi quis tortor id nulla ultrices aliquet.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (6, 'Schowalter, Denesik and Murphy', 'Arlöv', false, 'Nulla nisl.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (7, 'Marvin, Grimes and Smith', 'Fovissste', true, 'In congue.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (8, 'Ankunding Inc', 'Igbo Ora', true, 'Nullam molestie nibh in lectus.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (9, 'O''Keefe-Kuvalis', 'Dandian', false, 'Vivamus in felis eu sapien cursus vestibulum.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (10, 'Hessel-Leannon', 'Sanjiazi', false, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (11, 'D''Amore-Shanahan', 'Bauan', true, 'Nam tristique tortor eu pede.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (12, 'Williamson, Braun and Frami', 'Talas', false, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (13, 'Feeney Inc', 'Sebba', true, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (14, 'Batz Inc', 'Sendangkemulian', true, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (15, 'Schaefer-Kunze', 'Birobidzhan', false, 'Mauris sit amet eros.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (16, 'Langworth-Veum', 'Dąbie', true, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (17, 'Gorczany LLC', 'Kalayemule', false, 'Duis at velit eu est congue elementum.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (18, 'Lesch-Medhurst', 'Ryazanskiy', false, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (19, 'Baumbach-Mayert', 'Xihu', false, 'Sed vel enim sit amet nunc viverra dapibus.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (20, 'Rath-Macejkovic', 'Hyesan-si', false, 'Mauris lacinia sapien quis libero.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (21, 'Hilpert, Homenick and Rippin', 'Yanwan', false, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (22, 'Parisian-Gerhold', 'San Isidro', false, 'Proin eu mi.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (23, 'Schumm and Sons', 'Karanganyar', true, 'Cras non velit nec nisi vulputate nonummy.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (24, 'Carroll, Stiedemann and Koepp', 'Panikian', true, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (25, 'Bradtke, Rice and Metz', 'Sukadana', false, 'Sed vel enim sit amet nunc viverra dapibus.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (26, 'Mitchell-Hessel', 'Tupanciretã', true, 'Morbi ut odio.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (27, 'McDermott Group', 'Licuan', true, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (28, 'Rippin, Murphy and Orn', 'Zaoxi', true, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (29, 'Cruickshank, Schmeler and Franecki', 'Castelo', true, 'In blandit ultrices enim.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (30, 'Schinner-Kassulke', 'Castellon De La Plana/Castello De La Pla', true, 'Donec ut dolor.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (31, 'Konopelski-Koss', 'Chicama', false, 'Pellentesque at nulla.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (32, 'Swift, Hilpert and Wisoky', 'Maricá', false, 'Etiam vel augue.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (33, 'Abbott and Sons', 'Bukitkemuning', false, 'Nulla tempus.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (34, 'Feil-Kovacek', 'Canta', false, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (35, 'Bashirian, Gibson and Goldner', 'Wañgan', true, 'Donec quis orci eget orci vehicula condimentum.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (36, 'Schmitt Group', 'Marsh Harbour', true, 'Sed accumsan felis.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (37, 'Doyle Inc', 'Luodong', false, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (38, 'Heathcote, Huels and Kling', 'Sterling', true, 'Pellentesque viverra pede ac diam.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (39, 'Gleichner, Klocko and Wiegand', 'Baltimore', true, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (40, 'Doyle Group', 'Västerås', true, 'Morbi vel lectus in quam fringilla rhoncus.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (41, 'Orn-Ryan', 'Kavalerovo', true, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (42, 'Wunsch-Toy', 'Outeiro', true, 'Aliquam erat volutpat.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (43, 'Rippin-Deckow', 'Oster', true, 'Phasellus in felis.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (44, 'Johnson, Zulauf and Price', 'Pomabamba', false, 'Maecenas ut massa quis augue luctus tincidunt.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (45, 'Kunde-Murray', 'Puerto Asís', false, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (46, 'Luettgen, Koch and Beatty', 'Sergach', false, 'Nulla mollis molestie lorem.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (47, 'Connelly, Hettinger and Parisian', 'Bayān', false, 'Aliquam erat volutpat.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (48, 'Ebert and Sons', 'Watangan', true, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (49, 'Boyle-Sanford', 'Paris 12', false, 'Vestibulum sed magna at nunc commodo placerat.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (50, 'Haley-Jerde', 'Non Sung', false, 'Curabitur in libero ut massa volutpat convallis.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (51, 'Thiel LLC', 'Glugu', false, 'Etiam justo.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (53, 'Rowe, Bartell and Watsica', 'Lidköping', true, 'Integer ac leo.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (54, 'Sawayn-Wehner', 'Kamennogorsk', false, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (55, 'Okuneva, Greenfelder and Torphy', 'Aykhal', false, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (56, 'Bauch, Stamm and Wolff', 'Guilhabreu', false, 'Integer a nibh.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (57, 'Howell Group', 'Magok', false, 'Nullam varius.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (58, 'Olson-Kessler', 'Cravinhos', false, 'Pellentesque viverra pede ac diam.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (59, 'Boyle, Rice and Stamm', 'Yangchao', false, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (60, 'Kerluke Inc', 'Mambi', false, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (61, 'Wiza, Feest and Bechtelar', 'Qārah', true, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (62, 'Mosciski, Gerlach and Runolfsson', 'Benzilan', true, 'Fusce posuere felis sed lacus.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (63, 'Feest, Rempel and Strosin', 'Jindou', true, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (64, 'Gibson-Hirthe', 'Poniklá', false, 'Vestibulum rutrum rutrum neque.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (65, 'Kris LLC', 'Xicheng', false, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (66, 'Wiza, Boyle and Morissette', 'Dingtou', false, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (67, 'Kuhlman, Crona and Boyer', 'Iłowa', false, 'Etiam justo.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (68, 'Willms-Hessel', 'Kasturi', true, 'Aliquam quis turpis eget elit sodales scelerisque.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (69, 'Goldner and Sons', 'Ban Bueng', false, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (70, 'Kerluke, Batz and Towne', 'Dingdian', true, 'Vestibulum sed magna at nunc commodo placerat.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (71, 'Weber LLC', 'Korczyna', false, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (72, 'Mayer-Mueller', 'Kochetok', true, 'Nam tristique tortor eu pede.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (73, 'Heathcote-Glover', 'Nassarawa', true, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (74, 'Christiansen, Medhurst and Mertz', 'Juarez', false, 'Nullam molestie nibh in lectus.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (75, 'Rolfson-Collins', 'Palmerston North', false, 'Vivamus in felis eu sapien cursus vestibulum.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (76, 'Stokes-Schaden', 'Cumming', false, 'In blandit ultrices enim.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (77, 'Koelpin and Sons', 'Tessaoua', true, 'In blandit ultrices enim.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (78, 'Cole, Bogisich and Streich', 'Caen', false, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (79, 'Hagenes LLC', 'Ai Tu', true, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (80, 'Satterfield-Schneider', 'Binkolo', false, 'Curabitur at ipsum ac tellus semper interdum.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (81, 'Balistreri-Doyle', 'Morrison', true, 'Curabitur in libero ut massa volutpat convallis.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (82, 'Heidenreich, MacGyver and Nikolaus', 'Singaparna', false, 'Duis consequat dui nec nisi volutpat eleifend.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (83, 'Barrows-Zieme', 'Lagoa de Albufeira', true, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (84, 'O''Hara, Watsica and Steuber', 'Darhan', true, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (85, 'Leuschke, Kling and Witting', 'Mijiang', false, 'Pellentesque viverra pede ac diam.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (86, 'Brakus-Hilll', 'Burqah', true, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (87, 'Gulgowski, Skiles and Bechtelar', 'Karnice', false, 'Mauris ullamcorper purus sit amet nulla.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (88, 'Hyatt LLC', 'Jatirogo', true, 'Nulla ut erat id mauris vulputate elementum.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (89, 'Ward Group', 'Al Maḩfid', true, 'Proin eu mi.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (90, 'Collins, Larkin and Gerhold', 'Buena Esperanza', false, 'Pellentesque viverra pede ac diam.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (91, 'Leffler, Trantow and Boyer', 'Berehomet', false, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (92, 'Grimes-Bogisich', 'Lengshuitan', false, 'Nulla suscipit ligula in lacus.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (93, 'Brakus, Hayes and Wintheiser', 'Beidaihehaibin', true, 'Donec quis orci eget orci vehicula condimentum.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (94, 'Yundt-Jones', 'Zhonghouhe', true, 'Phasellus in felis.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (95, 'Leffler, Gibson and Borer', 'Berlin', true, 'Morbi non quam nec dui luctus rutrum.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (96, 'Howell-Kerluke', 'Ashley', false, 'Pellentesque eget nunc.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (97, 'Hansen, Gorczany and Farrell', 'Cholpon-Ata', true, 'Vivamus vestibulum sagittis sapien.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (98, 'Littel, Boyer and Shields', 'Budapest', false, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (99, 'McLaughlin Group', 'Khakhea', false, 'Etiam vel augue.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (100, 'Schowalter Inc', 'Buarcos', false, 'Integer ac neque.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (101, 'Zemlak-Gutkowski', 'Da’ao', true, 'Morbi ut odio.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (102, 'Batz, Runolfsdottir and Weimann', 'Masaraway', false, 'In quis justo.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (103, 'Greenholt, Adams and Breitenberg', 'Castries', true, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (104, 'Stroman Inc', 'Corralito', false, 'Nulla mollis molestie lorem.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (105, 'Kovacek, Auer and Thompson', 'Nagua', true, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (106, 'Miller-Stark', 'Gouyan', false, 'Nunc rhoncus dui vel sem.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (107, 'Bartoletti-Bednar', 'Oklahoma City', true, 'Etiam justo.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (108, 'Goyette-Armstrong', 'Manacsac', true, 'Nunc rhoncus dui vel sem.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (109, 'Lindgren, Boehm and Ziemann', 'Calçada', false, 'Morbi porttitor lorem id ligula.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (110, 'McClure, Feeney and Koss', 'Wang Saphung', true, 'Suspendisse accumsan tortor quis turpis.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (111, 'Koss Inc', 'Xiabaishi', false, 'Ut tellus.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (112, 'Hyatt, Romaguera and Gleason', 'Ljungby', false, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (113, 'Stamm Inc', 'Sacotes', false, 'Pellentesque viverra pede ac diam.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (114, 'Bogisich, Swaniawski and Schumm', 'Cuevas', false, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (115, 'Wolff-Murazik', 'Dampit', true, 'Suspendisse potenti.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (116, 'Swaniawski-Harber', 'Dongjingcheng', true, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (117, 'Hirthe, Wisozk and Kessler', 'Suva Reka', true, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (118, 'Bayer-Collier', 'Granja', true, 'Maecenas pulvinar lobortis est.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (119, 'Friesen, Upton and Waelchi', 'Xicheng', true, 'Aenean sit amet justo.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (120, 'Pollich-Leuschke', 'Lom Kao', true, 'Nulla mollis molestie lorem.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (121, 'Konopelski-Graham', 'Dongxi', false, 'Phasellus sit amet erat.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (122, 'Kemmer and Sons', 'Cojata', false, 'Nullam varius.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (123, 'Quitzon, Murphy and Bradtke', 'Wuyahe', false, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (124, 'Grady-Rippin', 'Boluo', false, 'Etiam pretium iaculis justo.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (125, 'Leuschke Inc', 'Yaozhou', false, 'Duis at velit eu est congue elementum.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (126, 'Casper-Koch', 'Borås', true, 'Cras in purus eu magna vulputate luctus.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (127, 'Yost-Abernathy', 'Fazhan', false, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (128, 'Quitzon, Hirthe and Powlowski', 'Timrå', true, 'Aliquam sit amet diam in magna bibendum imperdiet.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (129, 'Kuhn-Mayer', 'Guojiazhuang', true, 'Vestibulum ac est lacinia nisi venenatis tristique.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (130, 'Predovic-Nikolaus', 'Montréal-Ouest', false, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (131, 'Flatley Inc', 'Cihideung Satu', false, 'Nullam sit amet turpis elementum ligula vehicula consequat.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (132, 'Brekke, Weimann and Bayer', 'Yacuíba', false, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (133, 'Lockman-McCullough', 'Nglego', true, 'Morbi vel lectus in quam fringilla rhoncus.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (134, 'Glover Inc', 'Zeqin', true, 'Mauris sit amet eros.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (135, 'Carroll-Leannon', 'Benjamin Constant', false, 'Donec vitae nisi.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (136, 'Emmerich, O''Hara and Weissnat', 'Hinvi', false, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (137, 'Schumm, Cummings and Pfeffer', 'Huangpi', true, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (138, 'Davis, Nader and Spinka', 'Langnga', false, 'Duis consequat dui nec nisi volutpat eleifend.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (139, 'Romaguera, Mante and Cummings', 'Katori-shi', true, 'Donec semper sapien a libero.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (140, 'Considine, Cummings and Grady', 'Karlivka', false, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (141, 'Luettgen-Upton', 'Santa Maria', false, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (142, 'Ullrich Inc', 'Pucara', true, 'Vivamus in felis eu sapien cursus vestibulum.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (143, 'Ritchie-Lebsack', 'Madingou', true, 'Praesent lectus.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (144, 'Stehr LLC', 'Mulanay', false, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (145, 'Wilkinson Group', 'Galubakul', true, 'Vivamus tortor.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (146, 'Mills Group', 'Santa Cruz de Barahona', true, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (147, 'Lemke-White', 'Jing’an', true, 'Etiam justo.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (148, 'Shanahan-Morissette', 'Ravne', false, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (149, 'Stamm, Conroy and Windler', 'Águas Belas', true, 'Fusce posuere felis sed lacus.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (150, 'Borer, Kuhlman and Herzog', 'Río Segundo', false, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (151, 'Stoltenberg, Olson and Rutherford', 'Maqian', false, 'In quis justo.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (152, 'Haag, Turner and Harber', 'Kroczyce', false, 'Curabitur gravida nisi at nibh.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (153, 'Armstrong-Lehner', 'Gaoshi', true, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (154, 'Carter-Kohler', 'Manfalūţ', false, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (155, 'McKenzie, O''Keefe and Bergnaum', 'Montpellier', false, 'Aliquam non mauris.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (156, 'Murphy-Block', 'Shangdu', false, 'Mauris sit amet eros.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (157, 'O''Reilly-Hoeger', 'Kiikala', true, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (158, 'Turcotte Group', 'Qingtang', true, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (159, 'Hansen Group', 'Xianju', false, 'Suspendisse ornare consequat lectus.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (160, 'West, Schulist and Waelchi', 'Bahorí', true, 'Quisque porta volutpat erat.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (161, 'Wunsch, Lesch and Ullrich', 'Karlstad', false, 'Proin at turpis a pede posuere nonummy.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (162, 'Lind-Treutel', 'Lavezares', true, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (163, 'Lynch-Towne', 'Aracataca', true, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (164, 'Schiller and Sons', 'Caluire-et-Cuire', false, 'Proin at turpis a pede posuere nonummy.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (165, 'Wiza-Jakubowski', 'Kashihara', false, 'Nulla ut erat id mauris vulputate elementum.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (166, 'Franecki, Stracke and Boyle', 'Palkovice', false, 'Mauris sit amet eros.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (167, 'Turcotte-Cruickshank', 'Abbeville', false, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (168, 'Ullrich, Heidenreich and Walter', 'Al Balyanā', false, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (169, 'Hauck LLC', 'Banho e Carvalhosa', false, 'Curabitur at ipsum ac tellus semper interdum.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (170, 'Heaney, Waelchi and Haag', 'Benito Juarez', true, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (171, 'Heathcote, Bartoletti and Marvin', 'Radashkovichy', false, 'In sagittis dui vel nisl.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (172, 'Brekke, Schulist and Donnelly', 'Rivadavia', true, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (173, 'Mann-Bernhard', 'Eslāmābād', false, 'Proin at turpis a pede posuere nonummy.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (174, 'Halvorson, Cruickshank and Gerlach', 'Marína', false, 'Etiam faucibus cursus urna.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (175, 'MacGyver-Cormier', 'Amiens', true, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (176, 'McClure, Pollich and Kuhic', 'Anin', false, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (177, 'Gerlach, Daugherty and Dickinson', 'Qijia', false, 'Nunc nisl.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (178, 'Langosh, Brekke and Feil', 'Dashkawka', true, 'Nulla tellus.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (179, 'Wilkinson Inc', 'Yangyu', true, 'In congue.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (180, 'Crooks, O''Conner and Cummerata', 'Shentang', true, 'Mauris lacinia sapien quis libero.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (181, 'King Group', 'Cannes', true, 'Curabitur in libero ut massa volutpat convallis.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (182, 'Rohan-Miller', 'Krasnoarmeysk', true, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (183, 'Stiedemann, Vandervort and Bradtke', 'Ţahţā', false, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (184, 'Quigley, Greenholt and Watsica', 'Langtang', false, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (185, 'Will-Hills', 'Outeiro', true, 'Suspendisse potenti.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (186, 'Rippin Inc', 'Barão de Melgaço', true, 'Integer ac leo.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (187, 'Skiles-Deckow', 'Wulong', false, 'Integer ac leo.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (188, 'Wyman-Yundt', 'Ochota', false, 'Curabitur gravida nisi at nibh.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (189, 'Jones Group', 'Penhold', false, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (190, 'Ebert-Cruickshank', 'Ferkessédougou', true, 'Phasellus id sapien in sapien iaculis congue.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (191, 'Olson-Dickinson', 'Huangtugang', true, 'Duis consequat dui nec nisi volutpat eleifend.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (192, 'Thiel, O''Keefe and O''Hara', 'Nevel’', false, 'Morbi porttitor lorem id ligula.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (193, 'Trantow-Heidenreich', 'Peredovaya', true, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (194, 'Funk-Gerhold', 'Houjiachuan', true, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (195, 'Schiller, Willms and Boyle', 'Thành Phố Phủ Lý', false, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (196, 'Veum-Keebler', 'Kushtia', true, 'In eleifend quam a odio.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (197, 'Rolfson and Sons', 'Fernandópolis', false, 'Morbi a ipsum.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (198, 'Breitenberg-Rosenbaum', 'Oematnunu', true, 'Sed vel enim sit amet nunc viverra dapibus.');
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (199, 'Hammes, Marks and Bradtke', 'Sumberejo', false, null);
INSERT INTO public.cinema (id, name, city, is_open, rating) VALUES (200, 'Hyatt Group', 'Wudabao', true, 'Nam nulla.');
