create table film
(
    id           integer      not null
        primary key,
    title        varchar(255) not null,
    year         integer,
    release_date date         not null,
    duration     integer      not null,
    age_category varchar(255),
    genre        varchar(255),
    description  varchar(255),
    director     varchar(255),
    actors       varchar(255),
    image_url    varchar(255)
);

alter table film
    owner to postgres;

INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (2, 'Penguins of Madagascar', 2008, '1993-05-16', 834, 'TJ', 'Adventure|Animation|Children|Comedy', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', 'Cathi Pughe', 'Alex Thompson', 'http://dummyimage.com/234x100.png/cc0000/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (3, 'Cet amour-là', 1994, '2003-12-09', 443, 'XY', 'Drama|Romance', 'Integer a nibh.', 'Ches Gwilliams', 'Jane Smith', 'http://dummyimage.com/249x100.png/5fa2dd/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (4, 'Road Kill (a.k.a. Road Train)', 2004, '2039-07-12', 612, 'WY', 'Horror|Sci-Fi|Thriller', 'Aenean lectus.', 'Kathe Frazer', 'Chris Brown', 'http://dummyimage.com/197x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (5, 'Fortune, The', 2012, '2035-08-06', 724, 'AB', 'Comedy|Crime|Romance', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Tripp Kike', 'John Doe', 'http://dummyimage.com/189x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (6, 'Ted Bundy', 1999, '2029-07-26', 986, 'ZG', 'Crime|Drama|Thriller', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Myer Mateus', 'Ryan Garcia', 'http://dummyimage.com/192x100.png/5fa2dd/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (7, 'Trespass', 2007, '2009-12-26', 597, 'GG', 'Action|Crime|Thriller', 'Vivamus tortor. Duis mattis egestas metus.', 'Jamima Tax', 'John Doe', 'http://dummyimage.com/145x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (8, 'Bogus', 2000, '2038-08-05', 718, 'VB', 'Children|Drama|Fantasy', 'Vivamus in felis eu sapien cursus vestibulum.', 'Shelagh Southwood', 'Ryan Garcia', 'http://dummyimage.com/203x100.png/cc0000/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (9, 'Are You Here', 2009, '2039-10-16', 384, 'BF', 'Comedy', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', 'Joannes Tregensoe', 'John Doe', 'http://dummyimage.com/193x100.png/5fa2dd/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (10, 'Informers, The', 1997, '2022-11-01', 64, 'BO', 'Crime|Drama|Thriller', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Kort Carradice', 'Chris Brown', 'http://dummyimage.com/242x100.png/cc0000/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (11, 'Pippi in the South Seas (Pippi Långstrump på de sju haven)', 2009, '2022-05-15', 344, 'UD', 'Adventure|Children', 'Donec dapibus. Duis at velit eu est congue elementum.', 'Naoma Lochead', 'Jane Smith', 'http://dummyimage.com/245x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (12, 'Dark Star', 1999, '1998-10-21', 62, 'GL', 'Comedy|Sci-Fi|Thriller', 'Integer ac neque.', 'Darell Ashfield', 'Ryan Garcia', 'http://dummyimage.com/104x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (13, 'Miss Farkku-Suomi', 1992, '2034-09-08', 493, 'OZ', 'Drama|Romance', 'Morbi ut odio.', 'Elvira Piers', 'Sarah Wilson', 'http://dummyimage.com/109x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (14, 'Funky Forest: The First Contact', 2012, '2010-05-08', 95, 'AY', 'Comedy', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', 'Wilone Lusk', 'Sarah Wilson', 'http://dummyimage.com/242x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (16, 'Paris When It Sizzles', 1999, '1997-08-29', 373, 'NC', 'Comedy|Romance', 'Nullam varius.', 'Virgie Charles', 'Ryan Garcia', 'http://dummyimage.com/134x100.png/5fa2dd/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (17, 'No Logo', 1997, '2005-05-09', 97, 'AE', 'Documentary', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 'Bentlee Rule', 'Alex Thompson', 'http://dummyimage.com/134x100.png/cc0000/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (18, 'Kandahar (Safar e Ghandehar)', 2001, '1990-06-22', 225, 'EI', 'Drama', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'Sharia Paulillo', 'Olivia Martinez', 'http://dummyimage.com/245x100.png/dddddd/000000');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (19, 'Deep Blue Sea, The', 2012, '2030-12-26', 560, 'OG', 'Drama|Romance', 'Suspendisse accumsan tortor quis turpis. Sed ante.', 'Terese Klimmek', 'Michael Johnson', 'http://dummyimage.com/203x100.png/dddddd/000000');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (20, 'Dog Year, A', 2010, '2029-10-31', 828, 'DO', 'Comedy|Drama', 'Suspendisse accumsan tortor quis turpis. Sed ante.', 'Chic Deboo', 'Jane Smith', 'http://dummyimage.com/176x100.png/5fa2dd/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (21, 'Steamboat Bill, Jr.', 1998, '1990-05-02', 469, 'MG', 'Comedy|Romance', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 'Care Delepine', 'Alex Thompson', 'http://dummyimage.com/214x100.png/5fa2dd/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (22, 'Bikini Beach', 2006, '2004-04-03', 687, 'CE', 'Comedy', 'Quisque ut erat. Curabitur gravida nisi at nibh.', 'Trueman Jilkes', 'Emily Davis', 'http://dummyimage.com/249x100.png/cc0000/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (23, 'Swing Vote', 1990, '2033-12-28', 615, 'HV', 'Comedy|Drama', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Corissa Sjostrom', 'Chris Brown', 'http://dummyimage.com/178x100.png/cc0000/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (24, 'All I Want for Christmas', 2010, '2040-03-25', 131, 'IY', 'Children|Comedy', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', 'Portie Danks', 'John Doe', 'http://dummyimage.com/239x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (25, 'The Fox & the Child', 1992, '2004-09-08', 262, 'QI', 'Adventure|Children|Drama', 'Nulla tellus.', 'Lodovico Munns', 'Alex Thompson', 'http://dummyimage.com/209x100.png/dddddd/000000');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (26, 'Danika', 2009, '2015-03-08', 661, 'DL', 'Drama|Horror|Thriller', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 'Yardley Masarrat', 'Alex Thompson', 'http://dummyimage.com/101x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (27, 'Enough Said', 2011, '2032-02-19', 177, 'KP', 'Comedy|Drama|Romance', 'Fusce consequat.', 'Clarie Pepi', 'Olivia Martinez', 'http://dummyimage.com/143x100.png/cc0000/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (28, 'Disorganized Crime', 2001, '2012-10-01', 964, 'KU', 'Action|Comedy', 'Vivamus tortor. Duis mattis egestas metus.', 'Orland Eberts', 'Sarah Wilson', 'http://dummyimage.com/107x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (29, 'Carnival in Flanders (La kermesse héroïque)', 2004, '2003-10-09', 288, 'OS', 'Comedy|Romance', 'Suspendisse accumsan tortor quis turpis.', 'Dennis Duigenan', 'John Doe', 'http://dummyimage.com/157x100.png/cc0000/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (30, 'Gunfight at Dodge City, The', 2005, '2040-07-14', 281, 'PS', 'Western', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'Kendra Wonham', 'Alex Thompson', 'http://dummyimage.com/192x100.png/dddddd/000000');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (31, 'Quicksilver Highway', 1996, '2034-08-06', 452, 'QD', 'Horror|Thriller', 'Integer a nibh.', 'Sandor Reiach', 'Michael Johnson', 'http://dummyimage.com/223x100.png/dddddd/000000');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (32, 'December Boys', 2009, '2031-01-07', 668, 'HD', 'Drama', 'Nam dui.', 'Evelyn Bretelle', 'Ryan Garcia', 'http://dummyimage.com/195x100.png/dddddd/000000');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (33, 'Duellists, The', 2002, '2027-07-21', 620, 'WV', 'Action|War', 'Curabitur in libero ut massa volutpat convallis.', 'Ava Rannie', 'Ava Rodriguez', 'http://dummyimage.com/182x100.png/dddddd/000000');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (34, 'Trash', 1989, '2016-01-12', 252, 'WQ', 'Adventure|Crime|Drama|Thriller', 'Nulla ut erat id mauris vulputate elementum.', 'Lucita Kingscott', 'Emily Davis', 'http://dummyimage.com/135x100.png/cc0000/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (35, 'Secret of My Succe$s, The (a.k.a. The Secret of My Success)', 2010, '2028-04-09', 841, 'NO', 'Comedy|Romance', 'Praesent lectus.', 'Robbie Josovich', 'Ava Rodriguez', 'http://dummyimage.com/165x100.png/cc0000/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (1, 'Fred: The Movie', 2009, '1994-04-04', 148, 'AX', 'Horror', 'Proin eu mi.', 'Vidovic Gagg', 'Sarah Wilson', 'http://dummyimage.com/188x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (36, 'Another Gay Movie', 2003, '2025-02-22', 537, 'SL', 'Comedy', 'Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'Mac Draijer', 'John Doe', 'http://dummyimage.com/128x100.png/dddddd/000000');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (37, 'Seven Brothers (Seitsemän veljestä)', 1999, '2006-05-08', 697, 'TW', 'Animation|Comedy', 'Suspendisse potenti.', 'Manny MacCrachen', 'Ryan Garcia', 'http://dummyimage.com/164x100.png/dddddd/000000');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (38, 'Wild Orchid', 2007, '1994-06-12', 569, 'VW', 'Drama|Romance', 'Etiam pretium iaculis justo.', 'Suzette Dulanty', 'Ava Rodriguez', 'http://dummyimage.com/202x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (39, 'Touch', 1998, '2004-01-01', 616, 'ZP', 'Drama|Fantasy|Romance', 'Proin eu mi.', 'Mort Doerrling', 'Olivia Martinez', 'http://dummyimage.com/146x100.png/5fa2dd/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (40, 'Confidence Girl', 1992, '2006-12-30', 100, 'NY', 'Crime|Drama|Thriller', 'Nunc rhoncus dui vel sem.', 'Donetta Ryland', 'Emily Davis', 'http://dummyimage.com/227x100.png/cc0000/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (41, 'Screwed', 2006, '2013-10-30', 346, 'SR', 'Comedy', 'In eleifend quam a odio. In hac habitasse platea dictumst.', 'Jo-anne Murrhardt', 'Emily Davis', 'http://dummyimage.com/191x100.png/dddddd/000000');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (42, 'Wisdom of Crocodiles, The (a.k.a. Immortality)', 2009, '1997-10-18', 877, 'LK', 'Romance|Thriller', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Kitti Binnion', 'Sarah Wilson', 'http://dummyimage.com/131x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (43, 'God of Cookery (Sik san)', 2004, '2002-10-26', 311, 'FA', 'Comedy', 'Duis bibendum.', 'Dinny Oxnam', 'Emily Davis', 'http://dummyimage.com/177x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (44, 'Gold', 1995, '1994-12-22', 457, 'PE', 'Action|Adventure|Drama|Thriller', 'Suspendisse potenti.', 'Rocky Ornils', 'Sarah Wilson', 'http://dummyimage.com/103x100.png/5fa2dd/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (45, 'Man Without a Face, The', 2001, '2029-01-23', 423, 'AF', 'Drama', 'In quis justo.', 'Shauna Langhor', 'Ryan Garcia', 'http://dummyimage.com/105x100.png/dddddd/000000');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (46, 'Grand Illusion (La grande illusion)', 1998, '1993-07-27', 121, 'YG', 'Drama|War', 'Suspendisse potenti.', 'Aubrey Bowmaker', 'Jane Smith', 'http://dummyimage.com/179x100.png/dddddd/000000');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (47, 'Universal Soldier: Day of Reckoning', 2007, '2015-08-03', 807, 'AK', 'Action|Sci-Fi|Thriller', 'Sed accumsan felis.', 'Bendix Greydon', 'Ryan Garcia', 'http://dummyimage.com/144x100.png/cc0000/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (48, 'Little Bit of Soul, A', 2010, '2015-02-25', 186, 'JP', 'Comedy', 'In eleifend quam a odio.', 'Sheena Milbank', 'Ava Rodriguez', 'http://dummyimage.com/184x100.png/5fa2dd/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (49, 'My Dog Tulip', 2010, '1996-06-08', 411, 'EE', 'Animation|Drama', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 'Mohammed Joscelyne', 'Alex Thompson', 'http://dummyimage.com/185x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (50, 'Alice Doesn''t Live Here Anymore', 2004, '2017-01-01', 230, 'RR', 'Drama|Romance', 'Donec vitae nisi.', 'Blake Docker', 'Sarah Wilson', 'http://dummyimage.com/155x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (51, 'Afternoon Delight', 1979, '2006-02-23', 112, 'ET', 'Comedy|Drama', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', 'Ileana Carratt', 'Michael Johnson', 'http://dummyimage.com/227x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (52, 'Always Outnumbered', 2004, '2008-01-22', 402, 'EM', 'Drama', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Jennilee Sprake', 'Emily Davis', 'http://dummyimage.com/203x100.png/cc0000/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (53, 'Big Sur', 2008, '2040-01-13', 694, 'UX', 'Drama', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'Angelina Shillam', 'Emily Davis', 'http://dummyimage.com/224x100.png/5fa2dd/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (54, 'It Happened One Night', 2008, '2003-04-05', 221, 'EY', 'Comedy|Romance', 'Integer ac neque.', 'Irina Sheffield', 'Alex Thompson', 'http://dummyimage.com/152x100.png/5fa2dd/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (55, 'The Chase', 2001, '2006-07-05', 682, 'KD', 'Crime|Drama|Thriller', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', 'Josefa Pabel', 'Sarah Wilson', 'http://dummyimage.com/119x100.png/5fa2dd/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (56, 'Great Happiness Space, The: Tale of an Osaka Love Thief', 1999, '2015-08-25', 141, 'HD', 'Documentary', 'Ut at dolor quis odio consequat varius. Integer ac leo.', 'Early Barkworth', 'Ryan Garcia', 'http://dummyimage.com/157x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (57, 'BFFs', 2004, '2035-07-07', 15, 'MF', 'Comedy', 'Nullam molestie nibh in lectus.', 'Pren Dalziel', 'Sarah Wilson', 'http://dummyimage.com/126x100.png/dddddd/000000');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (58, 'About Time', 1990, '2012-06-05', 104, 'TC', 'Drama|Fantasy|Romance', 'Etiam vel augue. Vestibulum rutrum rutrum neque.', 'Jacquelynn Dani', 'Jane Smith', 'http://dummyimage.com/116x100.png/dddddd/000000');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (59, 'For the Boys', 1998, '1997-11-27', 601, 'FH', 'Comedy|Drama|Musical', 'Fusce posuere felis sed lacus.', 'Lori Maruska', 'Sarah Wilson', 'http://dummyimage.com/194x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (60, 'Bandaged', 2012, '2005-08-10', 990, 'CD', 'Thriller', 'Nunc purus. Phasellus in felis.', 'Carie Daughton', 'Olivia Martinez', 'http://dummyimage.com/237x100.png/5fa2dd/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (61, 'Breaker! Breaker!', 1963, '2030-04-11', 264, 'IC', 'Action|Adventure|Crime', 'Proin interdum mauris non ligula pellentesque ultrices.', 'Anna-diana Jon', 'Ryan Garcia', 'http://dummyimage.com/211x100.png/cc0000/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (62, 'Sarah Silverman:  We Are Miracles', 1992, '2028-02-05', 683, 'OL', 'Comedy', 'In quis justo.', 'Ernaline Bartol', 'Alex Thompson', 'http://dummyimage.com/231x100.png/dddddd/000000');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (63, 'Babylon 5: The Legend of the Rangers: To Live and Die in Starlight', 1995, '2020-03-31', 255, 'PY', 'Sci-Fi', 'Donec vitae nisi.', 'Tibold Petersen', 'John Doe', 'http://dummyimage.com/174x100.png/5fa2dd/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (64, 'Age of Innocence, The', 2002, '1998-03-16', 966, 'RV', 'Drama', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', 'Harmon Dakers', 'Chris Brown', 'http://dummyimage.com/182x100.png/cc0000/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (65, 'Eating Raoul', 2008, '2015-06-10', 35, 'RT', 'Comedy', 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', 'Bibbie Stebbin', 'Michael Johnson', 'http://dummyimage.com/174x100.png/5fa2dd/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (66, 'Ferryman, The', 2007, '2016-08-23', 361, 'GY', 'Fantasy|Horror|Thriller', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', 'Marris Baysting', 'Emily Davis', 'http://dummyimage.com/166x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (67, 'Cannibal Holocaust', 2008, '2038-04-08', 433, 'RH', 'Horror', 'Nulla justo.', 'Tiff Warriner', 'John Doe', 'http://dummyimage.com/208x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (68, 'Clueless', 2012, '1995-08-28', 615, 'JU', 'Comedy|Romance', 'Fusce consequat.', 'Demetris Oakwood', 'Olivia Martinez', 'http://dummyimage.com/105x100.png/dddddd/000000');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (69, 'Black Robe', 1968, '2005-01-04', 580, 'YK', 'Adventure|Drama', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 'Ortensia Manuel', 'Chris Brown', 'http://dummyimage.com/193x100.png/dddddd/000000');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (70, 'Dead or Alive 2: Tôbôsha', 1992, '2000-09-22', 645, 'PP', 'Action|Crime|Thriller', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 'Genny Milson', 'Jane Smith', 'http://dummyimage.com/136x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (71, 'Barbershop', 1992, '2027-09-05', 274, 'YD', 'Comedy', 'In sagittis dui vel nisl. Duis ac nibh.', 'Meryl Muckleston', 'Emily Davis', 'http://dummyimage.com/143x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (72, 'The African', 1999, '2032-01-24', 494, 'SN', 'Adventure|Comedy', 'Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'Brear Althrope', 'Michael Johnson', 'http://dummyimage.com/213x100.png/dddddd/000000');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (73, 'Ride Beyond Vengeance', 2011, '1999-07-05', 243, 'TY', 'Western', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Haskell Napthine', 'Ava Rodriguez', 'http://dummyimage.com/119x100.png/dddddd/000000');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (74, 'Red Like the Sky (Rosso come il cielo)', 1990, '2020-06-07', 6, 'KA', 'Drama', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 'Gabbie O''Boyle', 'Michael Johnson', 'http://dummyimage.com/113x100.png/5fa2dd/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (75, 'Time Lapse', 2008, '1991-06-01', 745, 'LT', 'Crime|Drama|Sci-Fi|Thriller', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Henrie Neeve', 'John Doe', 'http://dummyimage.com/157x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (76, 'Ra.One', 1995, '1998-07-29', 119, 'MY', 'Action|Musical|Sci-Fi', 'Nunc rhoncus dui vel sem.', 'Baxy Buse', 'Alex Thompson', 'http://dummyimage.com/184x100.png/dddddd/000000');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (77, 'War Wagon, The', 2001, '2017-08-17', 154, 'NF', 'Action|Western', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'Catriona Jenicke', 'Jane Smith', 'http://dummyimage.com/130x100.png/5fa2dd/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (78, 'Black Snake Moan', 2010, '2039-05-06', 895, 'YR', 'Drama', 'Nunc purus.', 'Sherline Dabbes', 'Olivia Martinez', 'http://dummyimage.com/180x100.png/cc0000/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (79, 'Flame and Women (Honô to onna) ', 2012, '2017-03-07', 315, 'GP', 'Drama', 'Praesent blandit lacinia erat.', 'Jaimie Vatcher', 'John Doe', 'http://dummyimage.com/188x100.png/5fa2dd/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (80, 'Peter Pan', 1996, '2008-01-17', 160, 'FK', 'Action|Adventure|Children|Fantasy', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', 'Linet Harmon', 'Ava Rodriguez', 'http://dummyimage.com/184x100.png/dddddd/000000');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (81, 'Watership Down', 1976, '2001-03-14', 283, 'KE', 'Adventure|Animation|Children|Drama|Fantasy', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 'Nev Purchon', 'Ryan Garcia', 'http://dummyimage.com/227x100.png/dddddd/000000');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (82, 'Godzilla vs. Megaguirus (Gojira tai Megagirasu: Jî shômetsu sakusen)', 2007, '2032-11-28', 927, 'VJ', 'Action|Sci-Fi', 'Integer a nibh. In quis justo.', 'Malcolm Red', 'John Doe', 'http://dummyimage.com/148x100.png/dddddd/000000');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (83, 'Hamlet', 2000, '2030-07-29', 549, 'KC', 'Drama', 'Aenean sit amet justo.', 'Margalo Arrow', 'Ryan Garcia', 'http://dummyimage.com/235x100.png/dddddd/000000');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (84, 'Brain, The', 2004, '1994-05-19', 69, 'VH', 'Horror|Sci-Fi', 'In hac habitasse platea dictumst.', 'Maressa Fairn', 'Emily Davis', 'http://dummyimage.com/195x100.png/dddddd/000000');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (85, 'Wild Hogs', 1999, '1998-01-29', 283, 'GE', 'Adventure|Comedy', 'Donec dapibus.', 'Cori Gaskall', 'Ava Rodriguez', 'http://dummyimage.com/152x100.png/5fa2dd/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (86, 'How to Make a Monster', 2006, '2037-03-23', 286, 'RE', 'Horror|Sci-Fi', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 'Benedikt Ebbles', 'Chris Brown', 'http://dummyimage.com/109x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (87, 'Lady Liberty', 2012, '1997-02-08', 54, 'QB', 'Comedy', 'Sed vel enim sit amet nunc viverra dapibus.', 'Ardenia Boutellier', 'Michael Johnson', 'http://dummyimage.com/237x100.png/dddddd/000000');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (88, 'Mary Reilly', 1985, '2012-09-04', 134, 'YB', 'Drama|Horror|Thriller', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Serena Lamprecht', 'Alex Thompson', 'http://dummyimage.com/169x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (89, 'Tangled Ever After', 2007, '2007-10-10', 59, 'ZW', 'Action|Animation|Children', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 'Ashil Biddwell', 'Michael Johnson', 'http://dummyimage.com/137x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (90, 'Inventing the Abbotts', 1996, '2030-10-09', 246, 'UH', 'Drama|Romance', 'Maecenas ut massa quis augue luctus tincidunt.', 'Pearce Crosland', 'Emily Davis', 'http://dummyimage.com/168x100.png/5fa2dd/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (91, 'Blood Simple', 1992, '2007-04-13', 685, 'XK', 'Crime|Drama|Film-Noir', 'Ut tellus.', 'Ros Malek', 'Ryan Garcia', 'http://dummyimage.com/249x100.png/cc0000/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (92, 'Arcana', 1971, '2031-04-17', 429, 'FY', 'Drama|Horror|Mystery', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 'Briny Ibbitson', 'Alex Thompson', 'http://dummyimage.com/126x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (93, 'Blood Moon', 2011, '2012-07-04', 875, 'HB', 'Drama|Horror', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', 'Stace Hartless', 'Ava Rodriguez', 'http://dummyimage.com/196x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (94, 'Art of Getting By, The', 1999, '2031-02-10', 272, 'SI', 'Drama|Romance', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 'Arturo Cotty', 'Ava Rodriguez', 'http://dummyimage.com/208x100.png/cc0000/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (95, 'Candyman', 1996, '2006-03-28', 447, 'VK', 'Horror|Thriller', 'In hac habitasse platea dictumst.', 'Fanchette Dupree', 'Alex Thompson', 'http://dummyimage.com/155x100.png/5fa2dd/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (96, 'Blood', 1993, '2031-07-10', 128, 'QZ', 'Crime|Drama|Thriller', 'Vivamus vestibulum sagittis sapien.', 'Johna Janeway', 'Emily Davis', 'http://dummyimage.com/157x100.png/5fa2dd/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (97, 'Unfaithfully Yours', 1986, '2025-06-03', 213, 'NA', 'Comedy|Romance', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', 'Arri Maliphant', 'Alex Thompson', 'http://dummyimage.com/137x100.png/5fa2dd/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (98, 'Stealing Rembrandt (Rembrandt)', 1993, '2022-01-19', 928, 'RY', 'Action|Comedy|Crime', 'Proin interdum mauris non ligula pellentesque ultrices.', 'Kimmy Challenger', 'Sarah Wilson', 'http://dummyimage.com/209x100.png/5fa2dd/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (99, 'Robot Carnival (Roboto kânibauru)', 2006, '2027-06-30', 147, 'GL', 'Animation|Comedy|Drama|Fantasy|Sci-Fi', 'Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'Immanuel Lidyard', 'Ryan Garcia', 'http://dummyimage.com/106x100.png/ff4444/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (100, 'Simpsons Movie, The', 2000, '2032-06-07', 782, 'ZV', 'Animation|Comedy', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'Fara Wright', 'John Doe', 'http://dummyimage.com/234x100.png/cc0000/ffffff');
INSERT INTO public.film (id, title, year, release_date, duration, age_category, genre, description, director, actors, image_url) VALUES (15, 'Fred: The Movie 2', 2009, '1994-04-04', 148, 'AX', 'Horror', 'Proin eu mi.', 'Vidovic Gagg', 'Sarah Wilson', 'http://dummyimage.com/188x100.png/ff4444/ffffff');
